### ISSUE TITLE
Update to use the latest Roslyn version and add support for C# 7

### ISSUE THREAD

**Issue by danroth27** [aspnet/Razor#1046]

**Comment by Eilon** [comment]
Two main things to do:

1. Reference the newer version of Roslyn
2. Evaluate all new language features to see what works and what doesn't.
   * Even for things that work, need to add tests for new syntax features to make sure it never breaks.

**Comment by Eilon** [comment]
Related issue w/ tuple syntax in generics: https://github.com/aspnet/Razor/issues/1070

**Comment by NTaylorMullen** [comment]
> Evaluate all new language features to see what works and what doesn't.

Went through the features and they all parse correctly (yay!). 

The work for this issue is then:
1. Reference the newer version of Roslyn
2. Add tests for C# 7 features

**Comment by rynowak** [comment]
FYI checking this in is blocked right now on us having the right versions for our tooling to consume.

**Comment by NTaylorMullen** [comment]
1696e2aebf07da475ce71178a448071058068078

**Comment by RehanSaeed** [comment]
Do we need to add `<LangVersion>latest</LangVersion>` or is this the default?

**Comment by rynowak** [comment]
Yes, you need to set `LangVersion`. MVC uses your projects' settings for compilation

**Comment by jcouv** [comment]
@Eilon @NTaylorMullen @ryanbrandenburg Just a heads-up: we plan to release C# 7.1 along with Visual Studio 2017 version 15.3 (and C# 7.2 with version 15.5). My understanding is that ASP.NET Core and Razor don't need official updates for users to adopt those new versions of the compiler. I have instructions from Damian which I collected [here](https://github.com/dotnet/roslyn/issues/18783#issuecomment-308510444).
What is your official adoption plan? Do you want me to ping you once nuget packages get published? Right now we have preview packages available.

Also, just to confirm, since I saw a discussion of LangVersion "latest" above: "latest" means latest minor version (7.0, 7.1, 7.2, 8.0, etc), whereas "default" means latest major (7.0, 8.0, etc). Most Visual Studio templates use "default" and we let people opt-into "latest". That avoids problems if different people on a team use different versions of Visual Studio 2017. What language version does ASP.NET Core project teamplates use? I'd recommend either specific version that gets ramped up, or "default".

**Comment by rynowak** [comment]
> What is your official adoption plan? Do you want me to ping you once nuget packages get published? Right now we have preview packages available.

There was a recent email thread about this - I've added you to that.

We ship a dependency on Roslyn which we use for runtime compilation. We will need to adopt your candidate (non-build number stamped) packages when they are available from myget, and sim-ship with you when we go to nuget.org. It sounds like the right folks are looped in on your side.

----------

Regarding the templates, I believe ours are `default`. It seems weird that we'd want to break from the norm, but I'll start a discussion on our side about setting `latest`. 

For Razor, it's our desire that runtime compilation should behave similarly to the rest of your project, so we want to get that information from the project compilation settings, and not hardcode anything.

**Comment by jcouv** [comment]
Sounds good. Just to clarify, I think "default" is good. I don't recommend changing to "latest".
