### ISSUE TITLE
__Generated__ ViewComponentTagHelper error in VS 2017 and Razor Language Services

### ISSUE THREAD

**Issue by Eilon** [aspnet/Razor#1074]
_From @Ponant on March 10, 2017 10:23_

Used the official release of VS 2017 with the [Razor Language Services](https://marketplace.visualstudio.com/items?itemName=ms-madsk.RazorLanguageServices) to properly render Tag Helpers with syntax highlighting etc. I made a new fresh project starting with .Net Core 1.1, and I can confirm that this issue is reproducible.

Create a View Component (here I call it `MainMenuViewComponent`) and invoke it in a view, say the `_Layout.cshtml`, as such

`<vc:main-menu></vc:main-menu>`

The app runs and correctly displays the result of the view component. However, close and reopen the view file (or VS 2017), and one gets

`Error CS0400 The type or namespace name '__Generated__MainMenuViewComponentTagHelper' could not be found in the global namespace (are you missing an assembly reference?)
`

Disabling Razor Language Services will remove this error, but you lose intellisense.
cc @madskristensen 

_Copied from original issue: aspnet/Mvc#5943_

**Comment by Eilon** [comment]
@rynowak / @pranavkm / @NTaylorMullen any ideas on this?

**Comment by NTaylorMullen** [comment]
Yup, the Razor/Mvc Razor.Host in Visual Studio don't support ViewComponentTagHelpers and we didn't do the ViewComponentTagHelpers hack the same way we did in the past (new technical limitations) so we left it as a half solution, you get IntelliSense but get View errors when open in VS. Here's the other options we considered:

1. Binding redirect the Razor bits in VS to latest. Barry pushed back on this option due to the testing reqs
2. Remove ViewComponentTagHelper support entirely.
3. Publish a facade package that has these fake classes: https://github.com/aspnet/RazorTooling/blob/2b7ac7dff1c0982c494c81f6da7292b722854664/src/Microsoft.AspNetCore.Razor.Design/Internal/AssemblyTagHelperDescriptorResolver.cs#L251-L264 and then require users to add that temp package to their application. Then we'd update our ViewComponentTagHelper resolution code  to generate bogus descriptors to give the appearance of working like it did before 😄.

**Comment by rynowak** [comment]
I thought the decision on this was `2. Remove ViewComponentTagHelper support entirely.`

**Comment by NTaylorMullen** [comment]
@rynowak Hmm. I thought we went back on that decision. I may be recalling our conversations wrong then; if that's the case we should take this opportunity to remove the support.

**Comment by svallis** [comment]
@rynowak @NTaylorMullen Removing support entirely would be a shame. Without using tag helpers to invoke view components you lose intellisense. Using them doesn't currently support optional attributes.

View components feel like they should such an integral part of ASP.NET Core, yet both of the current invocation methods have large drawbacks to either code writeability (intellisense) or code verbosity (no optional attributes). I can deal with that if things are improving, but if support is being removed for what is still the better invocation method of the two, should I be focusing elsewhere?

**Comment by rynowak** [comment]
@svallis - sorry if it was unclear, we were talking about temporarily removing support for VCTH from VS intellisense. If you have uses of VCTH in your code it would work just fine. As it is today, if you install the extension you get spurious errors in VS if you are using VCTH-es.

This feature will come back in full fidelity as soon as we are able to do it.

**Comment by svallis** [comment]
@rynowak Ah I see, thanks for the clarification, that's not quite so troubling. Point still stands with removal of intellisense (view component tag helpers would now be verbose *and* require resorting to the code/documentation constantly). Is the return to full fidelity attached to a milestone or on a timeline?

**Comment by Ponant** [comment]
@rynowak , it was a bit unclear indeed, I thought you decided to remove support the view component's intellisense altogether, which basically means excluding the best horse of the .Net Core from the VS2017 syntax highlighting  party.

**Comment by rynowak** [comment]
@svallis @Ponant - the plan is to bring this back as well as put the new "Razor Language Services" extension in the box in a VS Update. I don't have a date to share, other than that we're working on it as fast as possible.

**Comment by NTaylorMullen** [comment]
f302d68589864e66dcc6ed618710aa909952f7f8
