### ISSUE TITLE
Why Razor is part of MVC? Can we make a Razor website without MVC?

### ISSUE THREAD

**Issue by mnns** [aspnet/Razor#1601]
Makes no sense.

**Comment by davidfowl** [comment]
Why does it matter?

**Comment by mnns** [comment]
Kinda resembles the logic behind the decision to release ASP.NET Core MVC first without releasing a simple basic ASP.NET Core. So many people I've spoken to hate the fact that .NET Core comes without a straightforward non frameworked ASP/PHP option.

I wanna be able to write Razor without having to include MVC logic with it. It just doesn't make sense (at least from a technical/architectural POV).

**Comment by brockallen** [comment]
> Why does it matter?

Because you can only have MVC once in the DI system and the pipeline :)

**Comment by davidfowl** [comment]
> Kinda resembles the logic behind the decision to release ASP.NET Core MVC first without releasing a simple basic ASP.NET Core. So many people I've spoken to hate the fact that .NET Core comes without a straightforward non frameworked ASP/PHP option.

Razor Pages solves that problem in ASP.NET Core 2.0. It's pretty much what you want. As for it being coupled to "MVC", that should have no effect on your experience with it. If if makes you feel any better, it's built on top of the same primitives in MVC because we want the exact same feature set. The only difference is the "dispatcher". 

> Because you can only have MVC once in the DI system and the pipeline :)

This won't solve that problem. It's a *much* more fundamental problem than whatever this supposed decoupling would achieve.

**Comment by rynowak** [comment]
> Why Razor is part of MVC

It's not, Razor is a language, and is used to generate code. MVC's view engine is an implementation.

> Can we make a Razor website without MVC?

Yes, you will have to implement it.
