### ISSUE TITLE
Question on spaces and CR's with HTML tags on a line transition

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Razor#1602]
```html
<body>
    <div>
        @for (var i = 0; i < Model.People.Count; i++)
        {
            var person = Model.People[i];
            <text><p>Name: @person</p></text>
        }
    </div>
</body>
```
... doesn't render with the spaces and CR's from the transition line (:+1: this is the behavior I need) ...

> \<p>Name: person1\</p>\<p>Name: person2\</p>\<p>Name: person3\</p>

However ...

```html
<body>
    <div>
        @for (var i = 0; i < Model.People.Count; i++)
        {
            var person = Model.People[i];
            <p>Name: @person</p>
        }
    </div>
</body>
```

... **does** render with spaces and CR's ...

>             <p>Name: person1</p>
>             <p>Name: person2</p>
>             <p>Name: person3</p>

Was this behavior implemented because there are there cases where taking the whole line (spaces, CR, etc.) from the line transition into the rendered markup is useful?

I noticed that this is a standard behavior ...

```html
@if (Model.People.Count < 100)
{
    <text><p>There are less than 100 people.</p></text>
}
```
... \<text> also is required to render the para here without spaces and a CR.

**Comment by dougbu** [comment]
> Was this behavior implemented because there are there cases where taking the whole line (spaces, CR, etc.) from the line transition into the rendered markup is useful?

Yes, including whitespace is useful. Newlines are particularly important when reviewing / debugging generated HTML.

When minimization is important, the `<text>` element allows developers to exclude newlines and other whitespace in .cshtml files from the generated HTML.

FYI newlines and whitespace _within_ `<text>` elements are rendered. `<text>` actually controls transitions from C# "mode" to HTML mode. Whitespace before HTML elements is rendered otherwise.
