### ISSUE TITLE
PreserveCompilationContext needs to be set only if a project has any Razor files

### ISSUE THREAD

**Issue by pranavkm** [aspnet/Razor#2077]
[ ] Fix the sdk
[ ] Clean up Identity UI csproj

**Comment by pranavkm** [comment]
Didn't realize this earlier - NET.Sdk uses `PreserveCompilationContext` to determine if the deps file needs to be generated on desktop. See https://github.com/dotnet/sdk/blob/753207c916132c131052aa45196653bd7993b23a/src/Tasks/Microsoft.NET.Build.Tasks/build/Microsoft.NET.Sdk.BeforeCommon.targets#L71-L74

Mvc relies on the deps file to determine what assemblies to add as application parts. Making the change proposed by this issue would require us to make a couple other changes:

* Have something (Web.Sdk or a new target in Mvc) set `GenerateDependencyFile = true`. This is a requirement and we shouldn't rely on the vagaries of `PreserveCompilationContext` to enable it.
* Mvc does not treat the absence of the deps file as a failure. We only found out about this issue because the Microsoft.AspNetCore.Mvc.Testing's test fixtures expected it to be around. We should instead throw if Mvc cannot find a deps file for the app assembly.

**Comment by pranavkm** [comment]
cc @rynowak \ @DamianEdwards \ @javiercn

**Comment by javiercn** [comment]
> Mvc does not treat the absence of the deps file as a failure. We only found out about this issue because the Microsoft.AspNetCore.Mvc.Testing's test fixtures expected it to be around. We should instead throw if Mvc cannot find a deps file for the app assembly.

This would be a big breaking change. Apps that work right now will start breaking for no good reason. (The only scenario that breaks because of a missing dependency context is when you have components in class libraries).
The intended behavior is that if you are building an app in a single assembly you don't need anything and that if you have MVC components scattered across multiple assemblies, then you have to use the dependency context.

I think that as long as we generate the dependency files when you are referencing MVC we are fine. I do think that the best place to do that is the SDK.

**Comment by pranavkm** [comment]
We had a chat about this and the plan is to

a) Have the Web.Sdk set `GenerateDependencyFile = true` (unconditionally).
b) Continue with the basic premise of https://github.com/aspnet/Razor/pull/2083 to conditionally set `PreserveCompilationContext` in the Razor.Sdk
