### ISSUE TITLE
Codes to store c# codes

### ISSUE THREAD

**Issue by andrew-vandenbrink** [aspnet/Razor#2087]
If there is Pages, why not "codes" to store codes.

I'm aware the use case for asp.net teams is to use visual studio/source control -> build -> deploy
but there is this people like me who need to keep everything on the fly during runtime.

I know I can use c# script but there is a plan to make view compile updateable which means a good time to propose to make code also updateable.

At this moment if I need to add new code api I have to
- use c# script
- use c# script then compile, save dll somewhere, reference the dll and use c# script to call it (cumbersome)
- download the projects from source control, add the code, build dll and publish...

or just make it possible to call methods stored in razor page from another razor page?

**Comment by Eilon** [comment]
Hi @andrew-vandenbrink , the Pages folder just exists so that MVC knows which pages are Razor Pages, as opposed to MVC view pages. There is no need for a Codes folder because you can place code anywhere in the application.

There are no plans to support runtime compilation of regular C# code at this time. We're moving to a model where more of the compilation is done at build/publish time, and less is done at runtime, in part for performance reasons. (We didn't take away any features, but we changed the default experience for new projects.)
