### ISSUE TITLE
TagHelpers.output.cache is not updated correctly

### ISSUE THREAD

**Issue by ajaybhargavb** [aspnet/Razor#2104]
Repro:
- Create a simple app with a tag helper and RazorCompileOnBuild enabled
- Build and make sure `TagHelpers.output.cache` contains the serialized tag helper
- Delete the tag helper from the app
- Build again

Expected:
`TagHelper.output.cache` is empty

Actual:
`TagHelper.output.cache` still contains the deleted tag helper but the timestamp is updated

I am adding a test that covers this as we didn't have any.

cc @pranavkm @rynowak

**Comment by mkArtakMSFT** [comment]
Hey @ajaybhargavb, how critical is this? Should this be part of preview2?

**Comment by pranavkm** [comment]
The issue here is that the test is invoking the `/t:RazorGenerate` target in isolation without calling compile. Razor Sdk wires itself after `Build`, but does not call `Build` itself (i.e. do a `DependsOn="Build"`). We have two close analogies for this behavior - `XamlPrecompile` and `CreateSatelliteAssemblies` - both of which depend on build outputs, but don't invoke build. We should follow suit and leave the behavior as is. I'll change this to an integration test that calls Build multiple times.

**Comment by ajaybhargavb** [comment]
Great to hear there is no actual bug 👍 
Will we need to change all the other tests that invoke `RazorGenerate` target directly? Or is this the only test that relies on `Build` having to run?

**Comment by pranavkm** [comment]
Well, what do you know. There's a bug. Fixing it 😄

**Comment by rynowak** [comment]
You guys are pretty crazy.
