### ISSUE TITLE
Incorrect target element of nested tag helper

### ISSUE THREAD

**Issue by Stamo-Gochev** [aspnet/Razor#2144]
The following code:
```csharp
namespace CustomTagHelpers
{
    [HtmlTargetElement("outer-child-tag")]
    [HtmlTargetElement("child-tag", ParentTag = "parent-tag")]
    public class ChildTagHelper : TagHelper
    {
        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            output.TagName = "span";
            output.Content.SetContent("child content");
        }
    }

    [HtmlTargetElement("parent-tag")]
    [RestrictChildren("child-tag")]
    public class ParentTagHelper : TagHelper
    {
        public override void Process(TagHelperContext context, TagHelperOutput output)
        {
            output.TagName = "div";

            output.Content.SetContent("parent content");
        }
    }
}
```
aims at exposing the `ChildTagHelper` as `<child-tag>` when used inside `<parent-tag>` and as `<outer-child-tag>` on root level.

However, `<child-tag>` is also exposed on root level (screenshot from Visual Studio):
![image](https://user-images.githubusercontent.com/1857705/37204585-0a0c60e6-239a-11e8-9181-d5494c6a0df2.png)

Can you provide information why the above is happening and is there a way to update the definition:
```
 [HtmlTargetElement("child-tag", ParentTag = "parent-tag")]
```
so that it restricts the usage of `<child-tag>` in `<parent-tag>` only?

**Comment by mkArtakMSFT** [comment]
@NTaylorMullen, can you please look into this? Thanks!

**Comment by NTaylorMullen** [comment]
@Stamo-Gochev thanks for reporting this issue. It's definitely a valid bug on our end. To workaround it for now if you remove the `[HtmlTargetElement("outer-child-tag")]` from your `ChildTagHelper` it'll work as you expect.

For the dev who fixes this the bug is [here](https://github.com/aspnet/Razor/blob/2f79b90af5cbd9499f012c204f5bf4bb413ae61b/src/Microsoft.VisualStudio.Editor.Razor/DefaultTagHelperCompletionService.cs#L197-L203). Basically we blindly take rules from applicable descriptors.

**Comment by mkArtakMSFT** [comment]
Thanks @NTaylorMullen. @kichalla, can you please look into this? Thanks!

**Comment by mkArtakMSFT** [comment]
@kichalla, please evaluate the cost and assign the appropriate label.
