### ISSUE TITLE
TagHelper attributes with no value cannot be used in TagHelpers

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#220]
Razor does not correctly parse HTML attributes that have no value.

After playing around with the parse tree a bit I noticed that if you were to create HTML elements such as:
```
<input checked>
<input checked value>
```

The Razor parser does not generate an accurate syntax tree. This in turn results in the generated code not calling `WriteAttribute` and furthermore with `TagHelper`s does not allow us to pull the attributes from an HTML element easily.

Once this has been added we should also support this attribute syntax in Tag Helpers.

**Comment by dougbu** [comment]
when this bug is fixed, will need to modify the expectations in https://github.com/aspnet/Mvc/tree/dev/test/Microsoft.AspNet.Mvc.FunctionalTests/Compiler/Resources files as well as one HTML helper test file (see https://github.com/aspnet/Mvc/blob/dev/test/WebSites/MvcTagHelpersWebSite/Views/MvcTagHelper_Home/OrderUsingHtmlHelpers.cshtml#L72) that mimics current tag helper results

**Comment by NTaylorMullen** [comment]
With issue #289 all `TagHelper` bound attributes that are not typed `System.String` without a value will be invalid and cause a parse error. Do we want to do something special with say `bool` typed attributes, or any other types?

/cc @DamianEdwards

**Comment by DamianEdwards** [comment]
I think we just shouldn't support bound properties that don't have a value specified, i.e. parser error.

**Comment by ChrisKlug** [comment]
Just ran into this bug/feature/"possibility" and it is quite annoying. Not being able to add a TagHelper that handles the required attribute without having to add a value to the attribute is quite annoying and confusing. I can see this causing a heap of problems...

http://www.w3.org/html/wg/drafts/html/master/syntax.html#attribute-name-state, which is referenced in the code states that a space after the attribute name should move the parsing to the "after attribute name state", which says that if a character is found, it should go to the "attribute name state". 

Doesn't this mean that <input type="text" required /> should see the "required" as its own attribute without a value? Currently, the "required" attribute is combined with "/>" into "runtime />"...

HtmlMarkupParser.cs line 476 has a comment that says "Saw a space or newline after the name, so just skip this attribute and continue around the loop", which doesn't respect the w3.org spec in my opinion. It might not be XHTML or something, but should that really be a concern if HTML5 is what everyone is using, or should be using?

Sorry for long rant...

**Comment by NTaylorMullen** [comment]
@ChrisKlug Can completely understand the frustration. Razor actually as whole today doesn't parse attributes correctly even when not using `TagHelper`s. For instance: https://github.com/aspnet/Razor/issues/123. Hoping to get these issues all resolved to have less frustration :smile:

**Comment by DamianEdwards** [comment]
Just to be clear, the Tag Helper will be able to see the attribute once we fix other things we're currently working on. You'll be able to see the attribute from `TagHelperContext.AllAttributes`. This bug is specifically about having Tag Helper bound properties (i.e. properties on your Tag Helper class) be populated from attributes with no value.

Also, you'll be able to target a Tag Helper based on the existence of such a property using the `TargetElement` attribute.

**Comment by ChrisKlug** [comment]
Ok, great! It just caused me a heap of headscratching when I couldn't get my TagHelper to run when the "required" attribute didn't have a value. After a bit of looking, it seemed as it could be solved by changing some not too complicated things in the attribute parsing, but I don't know if that would affect something else... But fixing that seemed like a small thing that could be fixed by a quick pull request, but if it is bigger I will stay out of your way...

**Comment by NTaylorMullen** [comment]
@ChrisKlug The parsing logic change isn't much. Writing the tests for it will be the time sink, prob 20% feature 80% test time for this one :smile:

**Comment by NTaylorMullen** [comment]
6fa3e405af8abc628a9f76977d6cd25faa85994d
0882ff4a13f182402117958d80502fa414db4d3f
