### ISSUE TITLE
Attribute order from source is not preserved upon rendering

### ISSUE THREAD

**Issue by DamianEdwards** [aspnet/Razor#225]
This is annoying. The attributes for elements with Tag Helpers defined do not have their order preserved from the source CSHTML. They appear to be rendered in alphabetical order instead.

`<input type="submit" value="Log in" class="btn btn-default" />`
becomes
`<input class="btn btn-default" type="submit" Value="Log in" />`

**Comment by dougbu** [comment]
current behaviour remains as I described it in previous comment.  the Razor-level behaviour is Just Fine:tm:

however some MVC tag helpers still bind HTML attributes then put them back, moving those attributes to the end.  issues are limited to:
- `<input/>` tag helper binds the `type` and `value` attributes
- `<option/>` tag helper binds the `selected` and `value` attributes

think I'll leave this bug here but fix the above issues in the MVC repo...

**Comment by dougbu** [comment]
requires a few things:
- @NTaylorMullen's fix for #279
- consistently add attributes to `TagHelperExecutionContext` in source order
- use `PostElement` in `<link/>` and `<script/>` tag helpers and merge added attributes for original element
- use `PostElement` for `type="checkbox"` case in `<input/>` tag helper and merge added attributes for original element
- restore `TagHelperAttribute` close to original `AllAttributes` order in `TagHelperContentExtentions.CopyHtmlAttribute()` and (perhaps) rename that method to `CopyHtmlAttributes()`

**Comment by NTaylorMullen** [comment]
Talked about the importance of this fix with @Eilon and @dougbu, not important for beta5. Pushing it out.

**Comment by NTaylorMullen** [comment]
b0b4ac4f3f12299ec1c9301f0c7f67c7646e1c63
