### ISSUE TITLE
Rendering views into strings

### ISSUE THREAD

**Issue by onionhammer** [aspnet/Razor#2274]
There are lots of broken / half implemented libraries out there for rendering razor views to strings, it seems like this could be super simple if you guys wanted it to be. Why not include a simple / extensible helper class along with razor to render razor to a string / stream without the entire ASP.NET stack?

Since razor pages are compiled, the output could even be included in the same dll for proper strong typing rather than looking up views by path.

This would be super useful for things like HTML email templates

**Comment by benaadams** [comment]
Or to a Stream

**Comment by Eilon** [comment]
We do have a sample for this that I think @ajaybhargavb wrote: https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.RenderViewToString

**Comment by onionhammer** [comment]
@Eilon that looks like its got the right idea, but it doesn't make use of any of the pre-compilation / views-inside-of-libraries functionality

**Comment by mkArtakMSFT** [comment]
@ajaybhargavb, what would it take for us to update the sample @Eilon had pointed out above to use Razor SDK?

**Comment by mkArtakMSFT** [comment]
Ping @ajaybhargavb

**Comment by ajaybhargavb** [comment]
Discussed with @pranavkm. If we want the sample to be a generic view renderer without bringing any MVC concepts, we can do something similar to  https://github.com/aspnet/Razor/tree/dev/src/RazorPageGenerator which shouldn't be too much work. Any thoughts @pranavkm?

**Comment by pranavkm** [comment]
1. The sample that @Eilon pointed to - https://github.com/aspnet/Entropy/tree/dev/samples/Mvc.RenderViewToString - do things like discover build time compiled views along with views on disk since it's using Mvc's runtime view discovery. With the first class support for [Razor-UI in class libraries](https://blogs.msdn.microsoft.com/webdev/2018/03/01/asp-net-core-2-1-razor-ui-in-class-libraries) that we're introducing as part of 2.1.0, this should make things like sharing templates between web and non-web applications much better. 

2. We use the app that @ajaybhargavb pointed to - https://github.com/aspnet/Razor/tree/dev/src/RazorPageGenerator - as a way to code generate C# from Razor templates outside of Mvc scenarios. We use this to produce things like the developer exception page - https://github.com/aspnet/Diagnostics/tree/dev/src/Microsoft.AspNetCore.Diagnostics/DeveloperExceptionPage/Views. This would be a great starting point in case you'd like to build a templating library using Razor. 

At this point we don't have any plans for building a general purpose templating library using Razor. I'd encourage you to dig in to the links above. We'd be happy to help if you run in to any issues along the way.

**Comment by onionhammer** [comment]
@pranavkm So you use this 'for internal purposes only' sample to generate a developer page?

**Comment by pranavkm** [comment]
Unfortunately at this time, using Razor outside of Web \ Mvc isn't a priority for us. If the community stepped in, and created something in this space, we'd be happy to help with issues and promote it. 

> Also 'Mvc.RenderViewToString' fails hard when targeting net471

Could you file an issue for this in https://github.com/aspnet/Home/issues? Sounds like something we could look at.
