### ISSUE TITLE
Allow tag helper string attributes to honor null values

### ISSUE THREAD

**Issue by Tarig0** [aspnet/Razor#2313]
I have a view component that needs to be able to understand the difference between a null and empty string. when I use the following the view component is still retrieving an empty string.

```html
<vc:product-line-list exclude="@(Enumerable.Empty<string>())" selected="@ViewData["selected"]" has-key-nomen="@null"></vc:product-line-list>
```
aspnet/mvc#7708

**Comment by mkArtakMSFT** [comment]
Hi @Tarig0.

This has already been discussed a couple of times, so I'll try to go into more details here, trying to make the reasoning clear.
The support for this feature requires some breaking changes, yet the value add is not super big.
That's why we are not interested in providing this ability.
One alternative approach you can take though, is to wrap the value you want to pass to the tagHelper with a custom type, which will have a data you actually care about. Your tag helper's attribute should be updated to accept that object type and internally just refers to the property of the passed in instance.

**Comment by Tarig0** [comment]
Would it be feasible to change the behavior for string? Type in C8?

**Comment by Tarig0** [comment]
Thanks for the explanation, I understand the reason for not changing the behavior now that it is expected that null == "" and the passing of an wrapper object avoids the issue.

**Comment by mkArtakMSFT** [comment]
Glad we could help, @Tarig0. Closing this issue now.
