### ISSUE TITLE
Razor can't understand @ symbol (even @@) in pattern attribute

### ISSUE THREAD

**Issue by BachynskyiBohdan** [aspnet/Razor#2371]
Example:
`<input pattern="\w+(@)\w+(.)\w"/>` or `<input pattern="\w+(@@)\w+(.)\w"/>`

This approach trigger parser error:

> Description: An error occurred during the parsing of a resource required to service this request. Please review the following specific parse error details and modify your source file appropriately. 

> Parser Error Message: ")" is not valid at the start of a code block.  Only identifiers, keywords, comments, "(" and "{" are valid.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us, @BachynskyiBohdan.
@NTaylorMullen how is this supposed to be handled?

**Comment by NTaylorMullen** [comment]
Hmm, the escaped variant should be ok. @BachynskyiBohdan are you using ASP.NET Core? If so what version of VS are you using?

I ask because here's what I'm seeing on my end (expected, note the error only on the second line):
![image](https://user-images.githubusercontent.com/2008729/40557959-b8b2e5e0-6006-11e8-9806-603894223389.png)

**Comment by mkArtakMSFT** [comment]
Hi. We're closing this issue as no response or updates have been provided in a timely manner and we have been unable to reproduce it. If you have more details and are encountering this issue please add a new reply and re-open the issue.
