### ISSUE TITLE
Razor SDK - Option to have area views without an areas folder

### ISSUE THREAD

**Issue by nfplee** [aspnet/Razor#2425]
I’ve posted this as a question on stack overflow. It will help explain what I’m looking to achieve a little better:

https://stackoverflow.com/questions/50967430/asp-net-core-razor-sdk-class-library-area-views-not-within-areas-directory

I’d appreciate it if anyone could help out. 

I also see OrchardCore has achieved this but looking at the code I can’t seem to replicate this myself in a sample application I have built as a learning curve. 

It would be great if this was an option in the future.

**Comment by pranavkm** [comment]
```
return viewLocations.Concat(new[] {
            "../{2}/Views/{1}/{0}" + RazorViewEngine.ViewExtension
        });
```

Have you tried it without the ".."? The path for the file in the RCL would look like `/MyLibrary/Views/Home/Index.cshtml` which is what you want.

**Comment by pranavkm** [comment]
Could you share a minimal repro?

**Comment by nfplee** [comment]
[Sample.zip](https://github.com/aspnet/Razor/files/2138943/Sample.zip)

I've attached a very simple sample application if that helps. If you execute "dotnet run" in the Application directory and then navigation to "http://localhost:5000/MyLibrary" you will see the paths it tries to look for the views.

**Comment by pranavkm** [comment]
By default, the view engine paths for views are calculated relative to the application root. In this case, the views from MyLibrary are compiled with the location `/Views/Home/Index.cshtml`. There isn't a `MyLibrary` prefix which is what your view location expander expects. 

1) You could put the files under a second `MyLibrary` directory so that it gets the correct path e.g. `MyLibrary\MyLibrary\Views\Home\Index.cshtml`. This works both with runtime and build time compilation
2) The Razor Sdk uses well-known MSBuild metadata to calculate project relative paths. You may set the `Link` metadata for a file and Razor would use that. For instance, adding this to your project file would update all cshtml files to have a view engine path with the project name as a prefix:

```xml
<Target Name="UpdateTargetPath" BeforeTargets="AssignRazorGenerateTargetPaths">
  <ItemGroup>
    <RazorGenerate Include="@(RazorGenerate)" Link="$(TargetName)\%(RazorGenerate.RelativeDir)%(RazorGenerate.FileName)%(RazorGenerate.Extension)" />
  </ItemGroup>
</Target>
```

This does not work with runtime compilation - i.e. if you were to apply this to Application.csproj, it'll work for build time compiled views, but runtime compiled views would continue to use `/Views/Home/Index.cshtml`

**Comment by nfplee** [comment]
Thanks that seem to work. I still think this should be kept open as I think it should be an option to enable by default.

**Comment by pranavkm** [comment]
> I believe it should be an option to enable by default.

Using the `Link` metadata to specify target paths is a first class MSBuild feature. We don't plan on add any additional switches in addition to this.
