### ISSUE TITLE
Updating Razor Views while debugging in razor class libraries

### ISSUE THREAD

**Issue by IronMania** [aspnet/Razor#2426]
Hi,

I tested the new razor class libraries in ASP.NET Core 2.1.
There is one thing I REALLY miss there. When I debug my application, I can't update my razor Views in the class library. It works when I do that in my Webapplication, but not in my class library

This would be nice if it could be implemented.

**Comment by pranavkm** [comment]
The way this is meant to work is for the project to rebuild when it detects changes to referenced projects. If you're building on the command line, [`dotnet watch`](https://github.com/aspnet/DotNetTools/blob/dev/src/dotnet-watch/README.md) should took care of this. 

There's currently an issue in VS - https://github.com/dotnet/project-system/issues/3163 - that does not cause a project to rebuild when files in dependent projects change. Addressing it should address this issue. In the meanwhile, manually Ctlr-F5ing your project should cause the views in the class library to recompile and your app to pick it up.

cc @BillHiebert

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.

**Comment by joovnaz** [comment]
Hello,

unfortunately `dotnet watch` is not able to detect changes of RCL views.
Ctr-f5ing in VS doesn't fix either, because VS build cannot run in parallel.
Please give a look, is very annoying.

**Comment by flatproject** [comment]
Is there any way to work around the bug? The issue has been reported and tracked since April in the 
#https://github.com/dotnet/project-system/issues/3163 but no resolution.

How are other people using the RCL? At the moment I have to stop and start VS debug for every little style change I make to any view which is really frustrating and time consuming.

I tried the suggestion from @joovnaz but doesn't seem to work in VS.

**Comment by seriouz** [comment]
`dotnet watch` is no real solution to the problem, because it is way to slow for building up cshtml files. We have many developers in my company who are just working on the template side. When they press `ctrl+s` and tab over to the browser the change should be already visible there.
I have been told that a solution to use a [custom IViewLocationExpander](https://github.com/aspnet/Mvc/issues/8443) which resolves sub folders with cshtml-files at development environment [has been forbidden by their design](https://github.com/aspnet/FileSystem/blob/master/src/FS.Physical/PhysicalFileProvider.cs#L213).
My idea would be to relax the limitation and make it controllable through a config variable or the environment.

**Comment by seriouz** [comment]
@pranavkm Thanks for the tip! I'll investigate into this and call back on here.

**Comment by mkArtakMSFT** [comment]
@seriouz, did the suggestion @pranavkm has pointed out work for you?

**Comment by seriouz** [comment]
Sadly i was ill last week and had no real time to investigate further. But it's very high on my list now. I'll give feedback  soon, promised!

**Comment by seriouz** [comment]
I made it working for Razor Views. But how does it work for RazorPages don't they use a IFileProvider?

**Comment by pranavkm** [comment]
`RazorPages` use the same set of file providers for compilation and change tracking, so it should just work. Are you seeing otherwise?

**Comment by holajan** [comment]
I have the same problem. I can not find what the solution is. The impossibility to edit views during Visual Studio debugging is unthinkable, please help.
Why is this issue closed?

**Comment by flatproject** [comment]
There is no solution. The Razor team says its a DotNet team issue since April and the DotNet team has opened an internal ticket that we don't have visibility to see if any progress has been made. You would have thought so that if they are promoting so hard Razor Pages or Views in RCL at least to make sure that basic things work. [3163](https://github.com/dotnet/project-system/issues/3163#issuecomment-378674157)

**Comment by rathga** [comment]
The workaround with the PhysicalFileProvider mentioned above by pranavkm seems to be working well for me.  I can edit page views in my RCL whilst running and the changes are reflected.  Took a while to figure out, but it is as simple as adding this to startup.cs Configure()

services.Configure<RazorViewEngineOptions>(options =>
                options.FileProviders.Add(new PhysicalFileProvider(Path.Combine(HostingEnvironment.ContentRootPath, "..\\NAMEOFRCL")))
            );

Would be great if this was properly fixed though.
