### ISSUE TITLE
Localizer For Partial Views Issue (.Net Core)

### ISSUE THREAD

**Issue by PerdixDaedalus** [aspnet/Razor#2523]
Localizer For Partial Views Issue

Hi,

I already acquiring the strings from Localizer but only in the main view. How can I use the Localizer of the main view for the partial views inside of it? Because when I see the instance of Localizer of the partial views, it is trying to find the folder reference. I don't want that, I want it to use the Localizer of the certain main view that called the partial views. 

I also know that I can pass the Localizer as ViewData to the partial views but I'm not satisfied with that way.

Or is their a way to force what Localizer should be used?

Thanks in advance!

**Comment by pranavkm** [comment]
cc @ryanbrandenburg

**Comment by mkArtakMSFT** [comment]
Hi. It looks like this is a question about how to use ASP.NET Core. While we do our best to look through all the issues filed here, to get a faster response we suggest posting your questions to [StackOverflow](https://www.stackoverflow.com) using the **asp.net-core-mvc** tag.

**Comment by ryanbrandenburg** [comment]
If you explicitly mean passing the Localizer from a view to a partial, the only way I know of to pass objects between a partial and parent is ViewData. What about passing the Localizer as ViewData doesn't satisfy you? If you just want to access the resources from the parent file then it would be helpful for me to know what you are trying to accomplish with this setup. Because it seems to me that if you need a resource in both the Index and the Partial that it doesn't really belong to the Index, but in a shared resource which both views could inject.

**Comment by mkArtakMSFT** [comment]
Thanks for contacting us. We believe that the question you've raised have been answered. If you still feel a need to continue the discussion, feel free to reopen it and add your comments.
