### ISSUE TITLE
Handle unclosed C# code blocks better when intermingling HTML

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#2568]
Original issue: https://github.com/aspnet/Razor/issues/2566

Paste the following code with `test` as a TagHelper.
```
<test>
        @if (ShowFooter){
        { }
</test>
```
The end `test` gets understood as an invalid closing tag because of the above unclosed C# statement. In our journey of re-writing the syntax tree we should handle this scenario better and close out the incomplete C# code block once we see an unpaired closing tag.

@ajaybhargavb could you cost this based on what you feel it would take to do with the new world Html aware Razor parser?

**Comment by ajaybhargavb** [comment]
> @ajaybhargavb could you cost this based on what you feel it would take to do with the new world Html aware Razor parser?

Correct me if I am wrong but from what I understand currently, this would be a fairly major change in the way the CSharp parser works. I would say given the way it works, this is almost by design. Consider this case,
```c#
<test>
@if (ShowFooter){
</test>
var x = Foo;
}
```
When the CSharp parser encounters the first `<test>`, it needs to make a choice. If it closes out the statement block when it sees an Html block then `var x = Foo` will be parsed as Html. But we definitely don't want that. CSharp parser would need to have a LOT more context in order to know the difference between "I just forgot to close my statement block" vs "I just forgot to write a start tag".

**Comment by NTaylorMullen** [comment]
You've convinced me. @rynowak what do you think?

**Comment by rynowak** [comment]
lol why did you create a separate bug for this.
