### ISSUE TITLE
What is the purpose of "<Pack>$(IncludeRazorContentInPack)</Pack>"

### ISSUE THREAD

**Issue by rxelizondo** [aspnet/Razor#2599]
I noticed that my project file now contains the following entry:

```
  <ItemGroup>
    <Content Update="Views\xyz\abc.cshtml">
      <Pack>$(IncludeRazorContentInPack)</Pack>
    </Content>
  </ItemGroup>
```

Could someone tell me what is the purpose for this entry?

Thanks.

**Comment by NTaylorMullen** [comment]
If you didn't add this yourself then it's the result of a bug I fixed a while back. Basically if you copy/pasted a Razor file you'd get this.

Feel free to delete the item group entirely 😄 

As for what it does. It makes it so if you have a class library nupkg that contains Razor pre-compiled assemblies; you get to include the Razor files along side them so things like errors will be more verbose when things go wrong.

**Comment by rxelizondo** [comment]
@NTaylorMullen, Just the heads up.

I am using latest version of Visual Stdio (version 15.8.6) and this is still is an issue. I don't remember exactly what I did for this bug to surface but is definitely happening. The bug has not completely been fixed.

Thanks.

**Comment by NTaylorMullen** [comment]
> I am using the latest version of Visual Studio (version 15.8.6) and this is still an issue. I don't remember exactly what I did for this bug to surface but it is definitely still happening. The bug has not completely been fixed.

It's a result of the dotnet sdk you have installed. Could you try again using the latest dotnet available here: https://www.microsoft.com/net/download

**Comment by rxelizondo** [comment]
@NTaylorMullen, Sorry for taking so long to respond, I got side tracked and just got back to this.

I don't understand, I was under the impression that Visual Studio updates included updates to the latest versions of .NET SDKs. I figured that updates to SDKs that Visual Studio relies on to perform its work would be a major component to update as part of a Visual Studio update. 

Sp what the story here?

Thanks.

**Comment by NTaylorMullen** [comment]
> I don't understand, I was under the impression that Visual Studio updates included updates to the latest versions of .NET SDKs. I figured that updates to SDKs that Visual Studio relies on to perform its work would be a major component to update as part of a Visual Studio update.

You're absolutely correct. SDKs can get out of sync for multiple reasons:
1. If you build repos and SDKs get installed locally as part of build.
2. If you subscribe to early adopter feeds of Visual Studio, they can occasionally distribute bad versions of the SDK.
3. You've mucked with your path and Visual Studio is no longer detecting the dotnet sdk's it installs.

We've noticed a lot of bad sdk's on users boxes recently which has led us to believe there was a bad build of the SDK that somehow got distributed. We've since resolved the issue and hopefully, it should no longer be a problem moving forward.
