### ISSUE TITLE
Question on HTML5 void tag closure and a Razor tag helper exception

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Razor#393]
I was running into an issue with `gulp-minify-html`, where it was converting my XML input tags (written as self-closed) into unclosed elements prior to Razor receiving them. So, an `<input>` like ...
```
<input asp-for="name" type="text" class="txtbox short" />
```
was being minified into ...
```
<input asp-for="name" type="text" class="txtbox short">
```
prior to Razor doing it's bit. However, Razor chokes on this and gives you a ...
```
Found a malformed 'input' tag helper.
Tag helpers must have a start and end tag or be self closing.
```
Of course, closing void elements in HTML5 is optional per [HTML5 Spec 8.1.2.1 #6](http://www.w3.org/TR/html5/syntax.html#start-tags):
```
Then, if the element is one of the void elements, ... then there may be a single "/" (U+002F)
character. This character has no effect on void elements ....
```
So, is Razor not going to work with what would otherwise be valid HTML5 void elements when they aren't closed? It seems like valid HTML5 should be able to go right through Razor tag helper logic without a problem.

**Comment by GuardRex** [comment]
... and I'll add that using a tag helper prefix will solve this problem, but I was hoping not to have to use tag helper prefixes. It's more typing and more markup than I really want to see.

**Comment by dougbu** [comment]
@GuardRex Razor needs explicit (XHTML-ish) tag closure to determine the tag helper element content. Razor would otherwise get nearly as complicated as your browser. To avoid a hard-coded list of void elements (for example), elements that tag helpers target must either be self-closed or have an end tag.

But prefixes are a great workaround when using `gulp-minify-html` or other preprocessors that confuse Razor.

**Comment by GuardRex** [comment]
@dougbu I got you, thanks. I'll keep doing what I'm doing then.
