### ISSUE TITLE
Restrict '~' handling to only 'src' and 'href' attributes of HTML elements

### ISSUE THREAD

**Issue by Eilon** [aspnet/Razor#427]
Kind of related to https://github.com/aspnet/Razor/issues/417

Allegedly Razor will resolve paths of all attributes of all HTML attributes, which means that `~`'s will be stripped out regardless of whether the HTML (or Tag Helper) attribute represents a path or URL.

We should consider adding some new TagHelper attribute such as `[UrlProperty]` to indicate that Razor should code-gen path resolution code for the property.

**Comment by grahamehorner** [comment]
I agree however razor is also striping non-path attributes data-attrib="~some~data~" and this may be by design in razor for paths; but what if a tag requires the ~ and it's not a path. I think TagHelpers shouldn't have razor pre-process the tag attributes other than the know HTML attributes that are path related.

**Comment by Eilon** [comment]
@grahamehorner right, this bug is exactly to stop processing `~` in places where it's not a URL. Only `href` and `src` and perhaps some other specific HTML attributes should have URL processing.

**Comment by NTaylorMullen** [comment]
Attributes that I've found with URL support based on the HTML5 spec:
- href : `<a>`, `<area>`, `<link>`, `<base>`
- src : `<audio>`, `<embed>`, `<iframe>`, `<img>`, `<input>`, `<script>`, `<source>`, `<track>`, `<video>`
- action : `<form>`
- cite : `<blockquote>`, `<del>`, `<ins>`, `<q>`
- data : `<object>`
- formaction : `<button>`, `<input>`
- icon : `<menuitem>`
- itemid : everything
- manifest : `<html>`
- poster : `<video>`
- archive : `<object>`, `<applet>`

Discussing a right approach for this. There's a lot more attribute element combos then initially thought :smile:

**Comment by NTaylorMullen** [comment]
Talked with @DamianEdwards and since this capability is entirely dependent on which version of HTML you're using (HTML5, HTML4 etc.) we've decided to move this behavior from the core Razor parser into an auto-added `TagHelper` that exists in `Microsoft.AspNet.Mvc.Razor`. 

The `TagHelper` will be responsible for consuming the various attribute combinations listed above and normalizing the URLs. To prevent excess editor highlighting I've created  https://github.com/aspnet/Razor/issues/447 to allow this `TagHelper` to add default Razor functionality.

**Comment by NTaylorMullen** [comment]
Starting work on preliminary issues that will be required for this.

**Comment by grahamehorner** [comment]
@NTaylorMullen @DamianEdwards sounds great; happy to help out in reviewing and testing

**Comment by grahamehorner** [comment]
auto-added TagHelper; would this be a TagHelper that is registered with dependency injection and therefore a developer can override the default by registering the custom implementation?

**Comment by Eilon** [comment]
I believe anything with tag helpers can be overridden. It's part of the design of the feature :smile:

**Comment by grahamehorner** [comment]
@Eilon wasn't clear to me given the wording 'auto-added TagHelper' if this can be replaced by a custom TagHelper using config or dependency injection.

**Comment by Eilon** [comment]
I think what they mean is that it'll just be there by default in the project template. Not forced.

**Comment by NTaylorMullen** [comment]
@Eilon the idea is that it'd be auto-included in your views much like `HtmlHelper` is auto `@inject`ed into your view. The difference between the `TagHelper` to enable URL resolution and others is that it wont require an initial `@addTagHelper` because it'll be added by default. If you don't want the TagHelper you'll be able to `@removeTagHelper "*, Microsoft.AspNet.Mvc.Razor"`.

The thought behind the auto-adding approach is that not everyone will want to use `TagHelper`s in their project so auto-`@addTagHelper`ing a helper `TagHelper` will keep the experience they were used to in MVC5 but allow the ability to opt-out if need be.

**Comment by Eilon** [comment]
Got it.

**Comment by NTaylorMullen** [comment]
48a6b567d6d2194ce390599c37ef1e1b7c9c5a9e
