### ISSUE TITLE
Razor Comments Introduce Carriage Returns

### ISSUE THREAD

**Issue by RehanSaeed** [aspnet/Razor#428]
Using Razor comments, can cause extra carriage returns to appear in the generated HTML. This has been a problem in MVC 5 also.

```
<p>Paragraph 1</p>
@* Razor Comment *@
<p>Paragraph 2</p>
```

The above code generates the following HTML. You can imagine that with a lot of comments you get a lot of blank lines appearing in your code. If you really wanted a blank line to appear, you could add one yourself before the comment.

```
<p>Paragraph 1</p>

<p>Paragraph 2</p>
```

Ideally it should generate this HTML:

```
<p>Paragraph 1</p>
<p>Paragraph 2</p>
```

**Comment by NTaylorMullen** [comment]
@RehanSaeed The reason why you're seeing the extra carriage returns is due to the newline following the `*@`. To work around the issue you can do:

```
<p>Paragraph 1</p>
@* Razor Comment 
*@<p>Paragraph 2</p>
```

As for if this is right or not: Currently the only Razor comment we have only consumes the content it surrounds. `@*` to denote the begin of the comment and `*@` to denote the end. Therefore the `@*` comment is working as intended.

You're definitely not the first person to bring up such an issue however. Maybe filing an issue to add the ability to provide single line Razor comments (like C#'s `//`) would work well.

**Comment by RehanSaeed** [comment]
Adding single line comments sounds nice but that will still mean multi-line comments does not do what most developers expect. I can think of no reason when a developer would want it to add blank lines. The only way to get it to behave as expected is to use your workaround which is pretty ugly.

**Comment by NTaylorMullen** [comment]
@RehanSaeed The Razor comment clearly distinguishes were it starts and where it ends. HTML is white-space sensitive so adding newline consumption to a type of comment that has a start/end would lead to other issues. Take the following examples:

```
<p>
Hello World @* abc *@
</p>
<p>
Hello 
World @* abc *@
</p>
```

I'd definitely expect to see a newline in each of these examples. 

You could say that if `@* ... *@` is on its own line that it could then and only then consume the newline after it however that's why languages like C# invented things like `//` to deal with comments that consume a line to avoid magicish behavior.

**Comment by NTaylorMullen** [comment]
Created a "Create Razor single line comment alternative" issue: https://github.com/aspnet/Razor/issues/451

**Comment by danroth27** [comment]
We've decided to be smart about removing whitespace for any non-HTML content that occupies the entire line. So in addition to @RehanSaeed's example above, the following example:
``` html
@{
}
<!DOCTYPE html>
```
Should render just the doctype without any leading whitespace (which would be invalid). Also:
``` html
    @foreach (var item in items)
    {
        <li>@item</li>
    }
```
Should not render a line with four spaces before the list item.

**Comment by RehanSaeed** [comment]
@danroth27 Excellent! Imagine how much wasted bandwidth this change will save over the next decade!

**Comment by danroth27** [comment]
:smile:

**Comment by RehanSaeed** [comment]
I wrote a blog post about how much bandwidth this feature might have saved the internet [here](http://rehansaeed.com/minifying-html-for-asp-net-mvc/).
