### ISSUE TITLE
I Can't use @using static System.String in a razor view

### ISSUE THREAD

**Issue by Anderman** [aspnet/Razor#437]
I Can't use `@using static System.String` in a razor view

I am using Beta4 and mabe this issue is related to this bug?

Need to evaluate whether any C# 6 features will require changes to the Razor parser #44

**Comment by NTaylorMullen** [comment]
Hey @Anderman `@using static ...` was added in beta5 so stay tuned!

https://github.com/aspnet/Razor/issues/44

**Comment by dotnetchris** [comment]
Also this question is marked as a duplicate but no links and a quick search on issues didn't seem to turn up anything else similar

**Comment by NTaylorMullen** [comment]
@dotnetchris Pre-AspNetCore Mvc/Razor do not currently support C# 6 features. using static being one of those.

This is a duplicate of https://github.com/aspnet/Razor/issues/44 which was a catch all for C# 6 feature support.

**Comment by dotnetchris** [comment]
@NTaylorMullen i have no problems using the majority of C#6 with MVC 5.2.3 and Razor 3.2.3 via 

> Install-Package Microsoft.CodeDom.Providers.DotNetCompilerPlatform

**Comment by NTaylorMullen** [comment]
@dotnetchris Yup, there are some features that wont be possible. The reason why you can use some and not others is due to how Razor parses the page. For instance, in an `@{}` you can use the `?.` syntax because Razor says anything between the beginning `{` and the ending `}` is C#. However, in the `@using` case the Razor parser needs to fully parse that line to understand what the `@using` is pulling in; therefore, since Razor 3.2.3 doesn't understand C# 6 directly it doesn't know that `static` is a valid thing.

Hope this clarifies a bit.

**Comment by DzonnyDZ** [comment]
BTW: You can add e.g.
```xml
 <system.web.webPages.razor>
        <pages>
            <namespaces>
                <add namespace="static System.Globalization.CultureInfo"/>
```

to web.config in views folder to achieve similar result (for all views).

**Comment by SoulFireMage** [comment]
Doesn't work in the current MVC 5 implementation. 

![image](https://user-images.githubusercontent.com/2396080/34776243-1997c8d4-f60e-11e7-82c6-15ff93c7f30e.png)

**Comment by NTaylorMullen** [comment]
@SoulFireMage I'd suggest doing what @DzonnyDZ suggested in the web.config. `@using static` isn't directly supported by the Razor language outside of ASP.NET Core today.
