### ISSUE TITLE
Add ability for a TagHelper to state that it doesn't expect content

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#450]
This would enable `TagHelper` authors to specify how a `TagHelper` can be used when writing HTML. More importantly it would optionally allow void elements to be used with `TagHelper`s. It'd be specified via a `[TargetElement]`'s `CloseAfterOpeningTag` property.

Ex:

```C#
[TargetElement("input", CloseAfterOpeningTag = true)]
public class MyTagHelper : TagHelper
{
...
}
```

The default value of `CloseAfterOpeningTag` will be `false` with the special behavior of IF there are multiple `TagHelper`s working on a single HTML element which don't conflict then the `CloseAfterOpeningTag` value of the `TagHelper` that specifies its value will be used.

An invalid value combination is `CloseAfterOpeningTag = true` and `(user specified value to) CloseAfterOpeningTag = false` when multiple `TagHelper`s are targeting a single tag.

**Comment by danroth27** [comment]
@DamianEdwards

**Comment by GuardRex** [comment]
@NTaylorMullen I brought up a related issue in https://github.com/aspnet/Razor/issues/393 ... the problem there was that a Gulp task runner, like `gulp-minify-html`, to minify markup strips out void element's closing /, such that
```
<input asp-for="name" type="text"/>
```
becomes
```
<input asp-for="name" type="text">
```
which chokes the Razor parser and you get
```
Found a malformed 'input' tag helper.
Tag helpers must have a start and end tag or be self closing.
```
@dougbu explained
> Razor needs explicit (XHTML-ish) tag closure to determine the tag helper element content. Razor would otherwise get nearly as complicated as your browser. To avoid a hard-coded list of void elements (for example), elements that tag helpers target must either be self-closed or have an end tag. But prefixes are a great workaround when using gulp-minify-html or other preprocessors that confuse Razor.

... but that still doesn't sit well with me. I'd still greatly prefer not to have to use tag helpers to get around this. As it stands, we're going have a bazillion views with tag helper prefixes all over the place when going for minfied markup just because the Razor parser can't deal with unclosed void elements.

You are suggesting this feature for tag helper authors and that would seem to extend to solve my problem and allow the Razor parser to work with unclosed void elements. Is that a correct reading of your feature suggestion?

**Comment by NTaylorMullen** [comment]
@GuardRex Yup, that would be possible with this feature. By allowing `TagHelper` authors to define how a tag can be written (with the exception of `Void + Standard` combo) we're able to be smarter in parsing `TagHelper`s. The MVC `TagHelper`s would support their void element counterparts meaning your minifier would work perfectly :smile:

**Comment by GuardRex** [comment]
@NTaylorMullen Huge :+1: on that. Combined with possibly getting a [statement termination character on Razor directives (Razor/#444)](https://github.com/aspnet/Razor/issues/444), Gulp HTML minification will be a snap.

**Comment by danroth27** [comment]
We decided instead to just have a bool that allows a tag helper author to indicate if a tag helper includes content or not.

**Comment by NTaylorMullen** [comment]
/cc @DamianEdwards @Eilon Is it important to provide an API to render the `TagHelper`s back out as void if they're written in the void format (like what we do with self-closing today)?

If so I'd propose:

```C#
var output = new TagHelperOutput("input");
output.Format = TagFormat.Void; // => "<input>"
output.Format = TagFormat.Standard; // => "<input></input>"
output.Format = TagFormat.SelfClosing; // => "<input />"

// output.SelfClosing no longer exists
```

The alternative would be to translate (input file => runtime => final output) `<input>` => `output.SelfClosing = true` => `<input />`

I think eventually it'd be best to have the `TagFormat` approach but not convinced that it's immediately needed.

**Comment by NTaylorMullen** [comment]
Updated issue with decisions.

**Comment by NTaylorMullen** [comment]
e9292a0e308b661fb5bb4826f0b34d44183f3ea3
https://github.com/aspnet/Mvc/commit/1b51f6bca67e0f2e2d2c4ded15775174c9f3c789
https://github.com/aspnet/Mvc/commit/e1572f98ce979bb9c0879df1dd0ec58ff0034c7c
https://github.com/aspnet/Mvc/commit/21d96eb16a2b838da0ab36988ab9c927e03fdefb
https://github.com/aspnet/RazorTooling/commit/de629a8a16fff3b0b488d57a2d680c067da6c0f8

**Comment by GuardRex** [comment]
@NTaylorMullen Clarification ... the Razor parser can handle void elements (e.g., `<input>`, i.e., they don't need to be closed) as of beta7?

**Comment by dougbu** [comment]
@GuardRex correct. Razor can now handle void elements if a tag helper includes `TagStructure = TagStructure.WithoutEndTag` in the `[TargetElement]` association. Razor continues to handle void elements not associated with a tag helper.

**Comment by GuardRex** [comment]
@dougbu Awesome! :+1: Thanks. I'm looking forward to getting these tag helper prefixes out of my code, which were only there for the purpose of tricking the Gulp markup minifer into skipping those elements so that the Razor parser wouldn't choke on unclosed void elements. This is a great advance in Gulp markup minification.
