### ISSUE TITLE
Discussion: TagHelperContent APIs now HTML encode strings by default

### ISSUE THREAD

**Issue by rynowak** [aspnet/Razor#566]
This is the discussion issue for aspnet/Announcements#78
# 

We've changed the behavior of the existing `TagHelperContent` methods like `.Append(...)` and `.SetContent(...)` to HTML encode their input. A new set of companion methods have been added with names like `.AppendEncoded(...)` to append `string`s that are already properly HTML encoded.

See: https://github.com/aspnet/Razor/blob/dev/src/Microsoft.AspNet.Razor.Runtime/TagHelpers/TagHelperContent.cs

**Before**

```
output.Content.Append("<blink>");
output.Content.Append(HtmlEncoder.Encode("Hello, World!"));
output.Content.Append("</blink>");
```

**After**

```
output.Content.AppendEncoded("<blink>");
output.Content.Append("Hello, World!");
output.Content.AppendEncoded("</blink>");
```

Additionally, we retooled `.AppendFormat(...)` to be more useful in the obvious scenario of interpolating HTML text with untrusted formatting parameters. `AppendFormat` expects that the format-string is already HTML encoded, and that formatting arguments need to be encoded.

**Before**

```
output.Content.AppendFormat("<blink>{0}</blink>", HtmlEncoder.Encode("Hello, World!"));
```

**After**

```
output.Content.AppendFormat("<blink>{0}</blink>", "Hello, World!");
```

If you need to avoid encoding a format-argument, then use a wrapper such as `HtmlString`. Any type which implements `IHtmlContent` will get a chance to take control of the encoding process when used with `AppendFormat`.

**Comment by Suchiman** [comment]
I'm wondering if it should also contain a
```csharp
public TagHelperContent AppendFormat(FormattableString formatString)
{
    HtmlContentBuilderExtensions.AppendFormat(this, null, formatString.Format, formatString.GetArguments());
    return this;
}
```
overload.

Then you can have
```csharp
string unencodedText = "Hello, World!";
context.AppendFormat($"<blink>{unencodedText}</blink>")
//or even
context.AppendFormat($"<blink>{"Hello, World!"}</blink>")
```

**Comment by fhelwanger** [comment]
Is just me or it sounds like the ```AppendEncoded``` method would encode the string, but actually it's the other way around?

Maybe ```AppendRaw```, or something like that, would be a more straight-forward name?

**Comment by regisbsb** [comment]
Why not always encode unless is HtmlString?

**Comment by dougbu** [comment]
> `AppendFormat(FormattableString formatString)`

Interesting idea. Please file a separate issue in this repo with that suggestion.

> Maybe AppendRaw, or something like that, would be a more straight-forward name?

We've chosen `AppendHtml()`. See #3225.

> Why not always encode unless is HtmlString?

There's much less that's special about `HtmlString` in the new world. Other `IHtmlContent` implementations could also choose not to encode. Further existing `IHtmlContent` implementations include `string`s that are encoded mixed with some that are not.

**Comment by khalidabuhakmeh** [comment]
I was working with [Dave Paquette's Markdown](http://www.davepaquette.com/archive/2015/11/02/markdown-in-your-mvc-6-razor-pages.aspx) tag helper and found a bug with encoding too early.

We call out to the GitHub API to get raw markdown for our releases, which contains `\r\n` characters.

When doing something like this it fails to produce proper results.

```html
<markdown>@release.Body</markdown>
```

<img width="791" alt="home_page_-_site" src="https://cloud.githubusercontent.com/assets/228256/11744746/1fa84a3a-9fe1-11e5-8ffa-6ab2a79c2d7d.png">

The reason is that the `Content` is encoded before I can get access to it, which strips all the newline characters. In my opinion, this is a **bug** in Razor. If `GetContent` is encoded by default, it should, at least, give developers another method to get the `raw` contents of a tag.

**Comment by dougbu** [comment]
@khalidabuhakmeh it's impossible to reliably determine the "raw" contents because the `.cshtml` author must type in something that works correctly (and likely needs to keep the VS editor happy). Further the tag helper infrastructure cannot assume a tag helper will HTML encode the correct portions of the element body -- that separation is lost once `GetChildContentAsync()` completes. (A single expression in the body is not the general case.)

You mentioned "before I can get access to it". Why not massage the `release.Body` value before using the expression in the element's body?

**Comment by khalidabuhakmeh** [comment]
@dougbu thanks for your response.

> it's impossible to reliably determine the "raw" contents because the .cshtml author must type in something that works correctly.

I read that as `TagHelpers` are only meant to take in content from the `developer` and not a `user` of the application a developer builds. This behavior makes them all but useless for anything that requires user interaction. Sorry if that sounds harsh.

> Further the tag helper infrastructure cannot assume a tag helper will HTML encode the correct portions of the element body.

I would naively ask, If you cannot assume any of the tag contents is HTML encoded, then why encode any of it? Leave the encoding up to the creator of the `TagHelper`.

> You mentioned "before I can get access to it". Why not massage the release.Body value before using the expression in the element's body?

Markdown is very intentional. What I mean by that is every character and space matter towards the intention of the author. If I *massage* the input, I could inadvertently alter the user's intention.

I have solved this current problem with `TagHelpers` by not using them and reverting to `IHtmlHelper` extensions. It's lame but works as expected.

```csharp
@await Html.Markdown(release.Body)
```

**Comment by DamianEdwards** [comment]
@dougbu @khalidabuhakmeh The issue RE encoding of `TagHelperContent.GetContent` when accessing from inside a Tag Helper is being tracked in #643
