### ISSUE TITLE
Form tag action missing breaks view validation

### ISSUE THREAD

**Issue by GuardRex** [aspnet/Razor#606]
I just noticed that this markup ...
```html
<form id="contactform" asp-antiforgery="true" asp-action="contact" method="post">
```
... produces this markup ...
```html
<form id="contactform" method="post" action="">
```
... which, of course, hoses validation ...

![capture](https://cloud.githubusercontent.com/assets/1622880/11170138/b4571c9e-8b80-11e5-95a7-ba29cf8e96fb.PNG)

Is that the expected behavior?

**Comment by dougbu** [comment]
@GuardRex this is somewhat expected because we do not currently generate links to non-existent actions. However we're discussing making changes in this area, as @rynowak mentioned in the aspnet/Mvc#3512 issue.

Note the behaviour of MVC tag helpers should be discussed in the MVC repo. I suggest adding comments to aspnet/Mvc#3512 and closing this one.

**Comment by GuardRex** [comment]
@dougbu My bad. I didn't realize where it should go. I thought it might have been a Razor thing.

Moved to https://github.com/aspnet/Mvc/issues/3512
