### ISSUE TITLE
Provide access to the TagHelperDescriptor instance

### ISSUE THREAD

**Issue by sebastienros** [aspnet/Razor#627]
When providing `TagHelperDescriptor` instances dynamically, for instance from a database, I am targeting the same `TagHelper` type. I'd like it to get the descriptor it was called for, with some contextual data that is known when the descriptor is created.

**Comment by Eilon** [comment]
Talked to @DamianEdwards and this might be easy to do. If the descriptor is already there and just needs to be stashed into some context object, let's go ahead and do that.

If this is more complex, perhaps because the descriptor isn't available at the time we'd need it (e.g. compilation-time only, not at runtime), then we will move to Backlog.

**Comment by NTaylorMullen** [comment]
I'd mark this as a feature instead of a bug. We'd have to do quite a bit to get this working due to the descriptors lack of availability at runtime. So notttt easy, my recommendation is to move to backlog.

**Comment by rynowak** [comment]
No plans to do this
