### ISSUE TITLE
Rename `TagHelperContent.Append(IHtmlContent)` overload to be `TagHelperContent.AppendHtml(IHtmlContent)`

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#634]
@DamianEdwards and I discussed the current implementation of `TagHelperContent.Append(IHtmlContent htmlContent)` and felt that it makes more sense to append an `IHtmlContent` via an `AppendHtml` method rather than an overload to `Append`. In `TagHelperContent`s case we already have an `AppendHtml` helper method that wraps `string`s to ensure they aren't encoded. We should just overload its existing `AppendHtml` to take an `IHtmlContent` and remove the current `Append(IHtmlContent)` overload.

It's already decently confusing when determining how to append encoded/unencoded content. This would help make it clearer since `IHtmlContent` is HTML.

**Comment by dougbu** [comment]
The language here is never going to be quite right. An `IHtmlContent` implementation may or may not be pre-encoded. We're not talking about just `HtmlString`.

**Comment by DamianEdwards** [comment]
True, but surely `IHtmlContent` represents, you know, content that is HTML :smile: 

I think the rename makes sense here.

**Comment by dougbu** [comment]
@DamianEdwards exactly. User already knows it's `IHtmlContent`. So why repeat that information in the `IHtmlContentBuilder` (aspnet/HtmlAbstractions#4) or `TagHelperContent` method name?

**Comment by DamianEdwards** [comment]
Because when I tried to use it I didn't even see the overload of `Append` that takes `IHtmlContent`, given that we have a method called `AppendHtml`. I ended up calling `AppendHtml(myHtmlContent.ToString())` which is a pit of failure (I got encoded HTML, not at all what I wanted). My thinking was "I have something that knows it's HTML, I want to append it as HTML, so call `AppendHtml`".
