### ISSUE TITLE
_Layout rendering order...

### ISSUE THREAD

**Issue by SimonOrdo** [aspnet/Razor#649]
I was under the impression that Razor pages render in a LIFO fashion (innermost to outermost) in regards to partials.  This seems to hold true for the Body (@RenderBody()), but not for _Layout.cshtml.

It appears that _Layout.cshtml is rendering top to bottom, i.e. partials called in _Layout are rendered after _Layout has already begun executing.

Is this working as intended?

**Comment by pranavkm** [comment]
The rendering order only works for the view being rendered, not partials.

**Comment by Eilon** [comment]
There's nothing "special" about partials - they are run when they are invoked with a call to `@Html.Partial()` (or similar).

Layouts, on the other hand, have a composition model, and there's no way to know which layout to render until the "inner" content has run because that's what decides which, if any, layout page to use.

So, every view, with no exception, runs "top to bottom." And then after the view runs, the system checks if the `Layout` property was set, and if so, it then runs *that* page, and repeats the cycle.

**Comment by SimonOrdo** [comment]
Thank, @Eilon !  That cleared it up nicely for me.
