### ISSUE TITLE
@RenderSection("PageHeaderCssClass", false) renders white space after the content rather than before. 

### ISSUE THREAD

**Issue by byteful** [aspnet/Razor#677]
I am assuming this is a bug because the same code worked perfectly in MVC5. 

In my Layout.cs file I have the following code: 

```
class="pageHeader @RenderSection("PageHeaderCssClass", false)"
```

In my Index.cshtml file I have the following code: 

```
@section PageHeaderCssClass{pageHeader--homepage}
```

The expected output is: 

``` html
class="pageHeader pageHeader--homepage"
```

but instead it is generating the following: 

``` html
class="pageHeaderpageHeader--homepage "
```

**Comment by dougbu** [comment]
@ajaybhargavb ??

**Comment by NTaylorMullen** [comment]
I looked into this. The space is being parsed/arranged correctly but the writing of the attribute is actually failing. Seems the `prefix` and `value` are somehow being misordered at the `ViewBuffer` writing stage.

/cc @rynowak @pranavkm

**Comment by Eilon** [comment]
@ajaybhargavb please see if there is a low-risk fix here.

**Comment by ajaybhargavb** [comment]
The issue here is that the `RenderSection` method writes directly to the TextWriter before `WriteAttributeValue` is called which writes the prefix. This is the case with all the `Render***` methods that write directly to the output.
We have decided not to fix this issue at this time but moving to backlog to reconsider in the future.

@byteful, as a workaround we recommend you use `ViewContext` instead of `RenderSection`.

**Comment by Eilon** [comment]
@ajaybhargavb you mean using `ViewData`, not `ViewContext`, right?

In other words, doing the same thing as the default templates use for having a content page set the title for the layout page.

**Comment by ajaybhargavb** [comment]
@Eilon, yes. Edited.

**Comment by rynowak** [comment]
No plans to fix this
