### ISSUE TITLE
Asp.net core rc1 vs rc2 difference? (taghelpers)

### ISSUE THREAD

**Issue by AnderssonPeter** [aspnet/Razor#759]
i have the following code: 

```
@for (var i = 0; i <= Model.Products.Count / 3; i++)
{
    <div class="row">
        @foreach (var product in Model.Products.Skip(i * 3).Take(3))
        {
            <div class="col s12 m4">
                <div class="card hoverable">
                    <div class="card-image">
                        <img src="@product.ImageUrl" />
                        <span class="card-title">
                            @product.Title
                        </span>
                    </div>
                    <div class="card-content">
                        @product.Content
                    </div>
                </div>
            </div>
        }
    </div>
}
```

product.ImageUrl contains a path that starts with `~`, in rc 1 this was correctly translated to a relative path but in rc 2 its not the `~` just stays there in the output html. if i put a hard coded ```
<img src="~/images/balls-1440x743.jpg" />
``` then it correctly translates is to a relative path?

Do i need to define razor and the html helpers in some special order to get it to work correctly? (in `project.json`)

**Comment by Eilon** [comment]
I don't think this is deliberate, so probably a bug. Good find!

**Comment by NTaylorMullen** [comment]
Nope, this is by design. In RC1 the `~/` resolution was always runtime. This resulted in every img, script, link tag, basically any tag with an attribute that represented a URL having a `UrlResolutionTagHelper` run on it. In the end, for sites with a significant number of links which didn't use `~/`  you'd end uphaving a TON of unintended `TagHelper`s running where not needed.

In RC2 we added [CSS attribute support](https://github.com/aspnet/Mvc/blob/ef29749e724e87719a46ed8fe43d3cbbb6ce3d9d/src/Microsoft.AspNetCore.Mvc.Razor/TagHelpers/UrlResolutionTagHelper.cs#L37) to TagHelper attribute selection which enabled us to move `~/` determination to compile time; now, only tags that have an attribute value starting with `~/` have the `UrlResolutionTagHelper` applied to them (far more performant).

To fix your issue you can do one of the following:
1. `<img src="@Url.Content(product.ImageUrl)" />`
1. Remove `~/` from the variable and place it in the tag: `<img src="~/@product.ImageUrl" />`

**Comment by Eilon** [comment]
Interesting, I learned something new 😄
