### ISSUE TITLE
Create prefixes for tag helpers

### ISSUE THREAD

**Issue by NTaylorMullen** [aspnet/Razor#88]
This will involve modifying the ``@taghelper "assemblyname"`` directive to be something like ``@taghelper "assemblyname" "prefix"``.

This in turn will enforce certain restrictions on generating/understanding tag helpers.

Ex: If you do ``@taghelper "MyAssembly" "r-"`` that means that all tag helpers in ***MyAssembly*** must be prefixed with ***r-***.

```HTML
<r-my-taghelper /> <!-- Runs the my-taghelper helper -->
```

Should discuss if we want to support prefixes at the C# tag helper level.

**Comment by rosspace** [comment]
+1 for adding @ to the attribute. <a @controller="main" @action="index">
Razor uses the @ symbol to tell the developer that server side code follows so it makes sense to follow this standard.

**Comment by Klors** [comment]
I would suggest that a prefix that does not fit within standard HTML (including the upcoming Web Components) would be the best way to implement a feature like this.

I would also vote against making the syntax resemble the syntax of either razor or html elements too closely for a number of reasons. Most of which have probably been mentioned before in other comments, but which I'll state to reinforce them.

`<li><a controller="Home" action="Index">Home</a></li>`
This form is extremely ambiguous and even if it is created without clashes with current attribute names, there is no guarantee that future HTML specifications won't cause it to clash with valid client-side HTML.

`<li><@a controller="Home" action="Index">Home</@a></li>`
This form is better for having a non-standard element name, but I think you could then confuse it for (or it be indistinguishable from) a razor breakout into C#. Still suffers from potential HTML attribute clashes too.

`<li><a razor-controller="Home" razor-action="Index">Home</a></li>`
This form stops the standard attribute clash, though there is still a potential confusion with custom-attributes, but that's much less likely.

I'd have to agree with the first portion of the post by @glen-84 , the feature really only seems to be removing the need for the slightly ugly anonymous object/dictionary of attribute-value pairs in the HTML helpers and solutions to that of the form he suggested `<a href="@Url.Action("Index", "Home")" class="xyz" data-something="123">Link</a>` would seem to me to be the most useful and least troublesome/confusing option.

**Comment by dotWasim** [comment]
adding @ for attributes is perfect .. easy to implement and being noticed

**Comment by michaelherndon** [comment]
My two cents is:

Make prefixes optional. **This shouldn't be a zero sum feature.**

My time is valuable.  Prefixes require extra keystrokes even with intellisense / code completion. It will take extra keystrokes that current tag helpers would not require. If you know the ins and outs of html, it won't be that hard to simply view tag helpers as a server side version of web components.  Keystrokes and time are a finite resource.  So as someone who has a degree in design, I prefer the current simplicity of the tag helpers.  

That said, some people would prefer easy-to-scan code clarity over time spent on keystrokes. Making the prefix optional would sate both needs. 

This feature was targeted towards teams that have designers that only work with photoshop and markup. 

Ensure that designers are part of the feedback for this.  It would interesting to see how many of the comments in this list are from developers and how many are from people that are strictly designers that work with markup.

**Comment by mlmathews** [comment]
I think there should be some clear indication that an attribute is an ASP.Net attribute. A prefix convention seems like the simplest solution. The solution should not rely on Visual Studio syntax highlighting.

**Comment by egorpavlikhin** [comment]
+1 for @ prefix for **tags**, not attributes

I agree with @glen-84, this whole thing looks and smells an awful lot like webforms.

**Comment by danwalkerak** [comment]
I agree with @michaelherndon's comment.  Prefixes on both the html element (tag) and attribute level should be optional and left up to the designer/coder.

Personally I like the syntax that has no prefixes.

I definitely hate the data- prefix.  Server-side and client-side should never "see" each other.  If you force the data- syntax (e.g. data-action) then there would be no way to specify that data- attribute for the client.  As data- attributes are part of the HTML 5 spec (a client-side technology) it would be very confusing for people to start seeing it in the context of server-side code.  Especially when data- tags are mixed:  ( <li data-action="Home" data-clientId="4"> ).  Can you tell what is server-side and what is client side just by looking at that?

**Comment by safakgur** [comment]
**+1 for prefixes**
If I write a plain attribute, I expect it to show up on the client side.
Doesn't matter if it's `@`, `asp:` or `data-my-increadible-helper-attribute` :)
But there _has to be_ something that is _illegal_ in plain HTML so it's crystal clear that it is server side.

**Comment by danwalkerak** [comment]
After giving this some more thought - I believe TagHelpers are a terrible feature.

1.  You will never find a syntax that makes designers AND developers happy.
2.  We already have these kinds of helper tools via @Html and @Url helpers.
    a.  If @Html and @Url helpers don't have what you need, write an extension method that suits you.
3.  The potential for absolute mayhem is very high with this feature.  It dilutes the MVC/Razor framework.
4.  It doesn't add anything to Razor.  I would think this would be much more appropriate in the WebForms engine rather than the Razor engine.

I, apparently, fail to see what problem TagHelpers is trying to solve.  Is there a legitimate need for this or is it just someone's idea of a fun syntactic sugar?

Instead of TagHelpers I would think making the Razor engine extensible so that things like TagHelpers can be plugged into the engine would be a better use of Team Razor's time.  Make Razor extensible and then write TagHelpers as an example **optional** plugin that can be loaded via NuGet.

**Comment by glen-84** [comment]
> Instead of TagHelpers I would think making the Razor engine extensible so that things like TagHelpers can be plugged into the engine would be a better use of Team Razor's time. Make Razor extensible and then write TagHelpers as an example optional plugin that can be loaded via NuGet

I [agree](https://github.com/aspnet/Razor/issues/88#issuecomment-68180864) 100%.

@DamianEdwards Is it too late for a change like this?

**Comment by nvivo** [comment]
@danwalkerak and @glen-84,

> Instead of TagHelpers I would think making the Razor engine extensible so that things like TagHelpers can be plugged into the engine would be a better use of Team Razor's time.

Unless you are their manager, or you are a a very very active team member, it is quite arrogant of you to say how people that have been working on something for years should spend their time.

Now, based on your points, you apparently don't understand what it is and what it can do, even though you provided many arguments on why it shouldn't be done.

> I, apparently, fail to see what problem TagHelpers is trying to solve.

There you go.

>  Is there a legitimate need for this or is it just someone's idea of a fun syntactic sugar?

They make the code more readable, allow better tooling and also allow certain tag and attribute manipulation that are not currently possible unless you code the entire thing into a method, which again makes the code harder to understand. It's a good problem to solve.

There are some articles you can google for and the Community Standup on @shanselman's youtube channel gives some of explanations on why it was built and what they are planning to do with it.

Personally I think it is great that Razor is getting a better way to parse and generate html. This idea works great for angular and web components, worked great for asp.net webforms for years, there is no reason it wouldn't work for razor. People are completely used to this concept of translating a tag or attribute to something else.

> Make Razor extensible and then write TagHelpers as an example optional plugin that can be loaded via NuGet

It doesn't make sense to provide a separate dll for it because it is part of the compilation process. It makes as much sense as saying the C# compiler should require a nuget package to be able to parse "switch/case" statements.

You are probably confusing the tag helper as a "razor feature" that is being discussed here with the tag helpers that will be provided by default with MVC 6 for inputs and things like that. Those will come in nuget packages as part of mvc6 but that is a different project.

Also I'm amazed that the only point of this issue is to decide if tag helpers should have configurable prefixes or not. But very few people actually answered that.

**Comment by glen-84** [comment]
@nvivo,

I shouldn't have quoted the "better use of Team Razor's time" part, I was just agreeing with the opinion that TagHelpers would be better suited as a plug-in. I have a huge amount of respect for Damian and the rest of the team.

I also watch all of the Community Standup videos, but I can't remember anything (apart from the @Html.ActionLink example) that explained why TagHelpers are an improvement over HTML helpers.

As for being more readable:

```html
<a action="x">Link</a>
```

Is "action" a client or server attribute? How do you know?

Anyway, you're right about the fact that this is not the correct place to discuss this. In fact, there's no reason to discuss it at all anymore, as it's very unlikely that anything will change at this late stage.

**Comment by nvivo** [comment]
@glen-84, no problem, the answer was also more target at the author.

> Is "action" a client or server attribute? How do you know?

I think this is exactly the point of this discussion. One way is to add something like a prefix. They are proposing set the prefix at the top of the page, so you can do whatever you want to identify them.

```html
@taghelper "System.Web.Mvc.MvcDefaultHelpers" "asp-"
@taghelper "Telerik.PurchasedComponent.Helpers" "telerik-"
@taghelper "MyProject.MyHelpers" "myproject-"
...
<a asp-action="foo" telerik-something="bar" myproject-anotherthing />
```

This is very similar to how web controls were registered in asp.net, and that worked fine. In the end, you will probably have one or two prefixes registered in the web.config/config.json and get used to it. Visual Studio will have some syntax highlighting to differentiate registered server tags, and if you don't use VS, you can just lookup in the config file.

With Angular for example, you add a single `["module"]` to your config file, and suddenly a lot of tags that have nothing to do with the name of the module become valid in your html. You don't have any way to identify them, and you need to look at the documentation to know that an attribute "allow-select-row" will be valid if you add the `["ngsmartgrid"]` to your app, and people seem fine with that. Razor is going in a much better path allowing you to add prefixes in my opinion.

Also there are some interesting uses. Imagine you could do something like:

```html
<script asp-src-debug="~/src/**/*.js" />
<script asp-src="~/bundle.min.js" />
```

That would render a single script tag for production and multiple for development. Integrates both with grunt/gulp and web optimization and seems much nicer than the current approach with Html Helpers and method calls.

**Comment by glen-84** [comment]
@nvivo You can also do that with the [&lt;environment&gt;](https://github.com/aspnet/Mvc/issues/1553) tag.

**Comment by mvkorobkov** [comment]
voting to keep html standard and use helpers only inside values of attributes
like <a href="@Url.Action("Index", "Home")" -  just maybe good to implement short smart version that will understand attribute name and react correctly -  mean <a href="@(Home, Index, ... )"

**Comment by henriksen** [comment]
My vote is to have a default prefix (`asp:`) and allow custom prefixes at the top of the file (or in `Layouts`) like so: 
    @taghelper "System.Web.Mvc.MvcDefaultHelpers" "asp-"
    @taghelper "Some.Custom.Component" "xyz:"

Perhaps even allow a TagHelper library to specify it's own default prefix? 

I like the `:` since that makes a clear separation between client prefixes (`xyz-`) and server prefixes (`xyz:`), but that could be overridden with a custom prefix. I'm assuming it won't break a lot of existing tools that work with HTML. 

I'd like to keep the prefixes on the attributes since I'd like minimal confusion for non-server-side-developers (designers, front-end) and better compatibility with tools that wants to parse your HTML.  For instance, it's not a given that your HTML guy is working in Visual Studio and most tools will not understand `<asp:a ...>`.

I don't like the `data-prefix-attribute` suggestion. These names will never make it to the client, seems like a waste to make them conform to some client-specific standard. Although, it would prevent a bunch of validation errors if you pull a Razor file into some other HTML designer. In the end, I personally think the benefit is too small.

I agree that a prefix is needed, the confusion and ambiguity is just to much without, like demonstrated so many times in this thread. 

I think taghelpers can be a valuable tool for increasing the compatibility between different tools and different groups of people.

**Comment by kayzser** [comment]
+1 for prefix

**Comment by autonomatt** [comment]
+1 for standard attributes. A prefix is just more to type. I still like Spark the best, but these tag helpers are making me reconsider Razor.

**Comment by pdaoust** [comment]
+1 for prefixed attributes, but prefixed in the HTML5-like way. And without a `data-` prefix, because then it looks like it's for client-side use. `asp-` looks the nicest so far, because it's clear that it's meant for the server side.

As for custom elements, I'm not sure. I'd lean towards a prefix there too, in keeping with HTML5 custom elements, but then it won't be clear from the code that an element is server-side rather than client-side. I think you might have to use an xmlns-style (or WebForms-style) prefix, like `<asp:custom-element />`.

Anyhow, very excited to see this coming to ASP.NET!

**Comment by asp** [comment]
Please remove me from this thread. Is it my fault my initials are "asp"?

**Comment by glen-84** [comment]
Alan Pater (asp),

Click the "Unsubscribe" button on the right [here](https://github.com/aspnet/Razor/issues/88).

**Comment by Lone-Coder** [comment]
+1 for standard attribute. Terseness is beautiful!

**Comment by nvivo** [comment]
Someone should close this issue... This has already been decided a long time ago.

**Comment by pdaoust** [comment]
@nvivo Oh! What was the final decision? Perhaps someone with the authority to close this issue should  put it as the final comment before they close it.

**Comment by StuartQ** [comment]
I think @DamianEdwards is probably best placed to clear things up?  I believe from watching the community standups that the design have evolved quite a bit since this was raised.  This Youtube link should help https://www.youtube.com/watch?v=Tv9pv1FYP1A

**Comment by DamianEdwards** [comment]
This is resolved by #309. You can now set an optional prefix at any level that must be present on an element for it to be considered for Tag Helper processing. 
Thanks for all the feedback.

**Comment by DamianEdwards** [comment]
And here's what the VS editor currently looks like when working with Tag Helpers:

![image](https://cloud.githubusercontent.com/assets/249088/6872498/e3211722-d466-11e4-9176-0d9cdd2271d2.png)

**Comment by jerrydx** [comment]
I think that "@" is better that "asp-" ....
