### ISSUE TITLE
Add information about error file when precompilation error occurs

### ISSUE THREAD

**Issue by msmolka** [aspnet/Razor#951]
I'm trying to precompile views  and it results following error:

Running Razor view precompilation.
C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\DotNet\Microsoft.DotNet.Publishing.targets(149,5): Error :  (5): Encountered end tag "a" with no matching start tag.  Are your start/end tags properly balanced?

I have a lot of cshtml files, so in which file error occurs? I've search all my files for <a and </a and the amount of result is the same. I'm spending now second hour on finding place where error occurs and still no lack.

Please add better error messages when producing errors.

UPDATE:
After no luck with finding an issue. I removed ALL cshtml files from my project, and have exactly the same error? How it is possible when there is no cshtml file?

**Comment by Eilon** [comment]
@msmolka maybe there's a left-over CSHTML file in the `bin/**` or `obj/**` folder?

**Comment by Eilon** [comment]
@ajaybhargavb can you look at how we can improve our error reporting here?

cc @NTaylorMullen @rynowak @pranavkm FIY

**Comment by pranavkm** [comment]
The underlying issue is that the file path in `RazorError` is not always set. In Mvc, the compilation service null-coalesces it with the path of the being compiled (https://github.com/aspnet/Mvc/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor/Internal/RazorCompilationService.cs#L98), something that doesn't happen in precompilation - https://github.com/aspnet/MvcPrecompilation/blob/dev/src/Microsoft.AspNetCore.Mvc.Razor.ViewCompilation/Internal/PrecompileRunCommand.cs#L67.

**Comment by ajaybhargavb** [comment]
Should this issue be moved to MvcPrecompilation?

**Comment by pranavkm** [comment]
I think we had an issue ages ago to always have the file path which we gave up on since it meant modifying all the APIs given the lack of a context object during Razor parsing. We had other issues (like https://github.com/aspnet/Razor/issues/803) that involved flowing more context thru the system once we switched to Razorevolution - we could use those to track the underlying work here.

**Comment by ajaybhargavb** [comment]
Closing as this is fixed in https://github.com/aspnet/MvcPrecompilation/issues/67
